[project]
name = "app"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiokafka>=0.13.0",
    "alembic>=1.18.1",
    "fastapi[standard]>=0.128.0",
    "psycopg[binary]>=3.3.2",
    "redis>=7.1.0",
    "sqlmodel>=0.0.31",
    "tenacity>=9.1.2",
]
