{{- if .Values.outboxWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-api.fullname" . }}-outbox-worker
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
    app: order-service
    component: outbox-worker
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.outboxWorker.metricsPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rest-api.selectorLabels" . | nindent 4 }}
    component: outbox-worker
{{- end }}
